server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/user_db
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:local-dev-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:admin}:${MONGO_INITDB_ROOT_PASSWORD:local-dev-password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/user_query_db?authSource=admin
  kafka:
    consumer:
      group-id: user-service-group

app:
  admin:
    email: ${ADMIN_EMAIL:admin@company.com}
    password: ${ADMIN_PASSWORD:admin123}
  kafka:
    topics:
      user-events: user-events
