spring:
  application:
    name: officer-service
  profiles:
    default: dev
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      company-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - feign.FeignException$NotFound

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
eureka:
  client:
    enabled: false
