name: Dev Environment
values:
  - key: accessToken
    enabled: true
    value: ''
  - key: refreshToken
    enabled: true
    value: ''
  - key: expiresIn
    enabled: true
    value: ''
  - key: ''
    enabled: true
    value: ''
