name: 'Local'
values:
  - key: apiGatewayBaseUrl
    value: 'http://localhost:8080'
    enabled: true
  - key: userServiceBaseUrl
    value: 'http://localhost:8081'
    enabled: true
  - key: companyServiceBaseUrl
    value: 'http://localhost:8082'
    enabled: true
