spring:
  application:
    name: user-service
  profiles:
    default: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
eureka:
  client:
    enabled: false
